# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://nancytao.com
title: Nancy Tao
email: nancytao@gatech.edu
author: Nancy Tao
description: > # "Nancy Tao is a computer science student at Georgia Tech interested in artificial intelligence and design."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty