# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://nancytao.com
title: Nancy Tao
email: nancytao@gatech.edu
author: Nancy Tao
description: Nancy Tao is a computer science student at Georgia Tech interested in artificial intelligence and design.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# Settings for analytics helper
# Set 'provider' to false to turn analytics off globally.
analytics :
    provider : google
    google :
        tracking_id : 'UA-69825583-1'